libname log "C:\Documents and Settings\STD\Desktop\FB";run;
DATA D V;
SET LOG.BITS;
IF RANUNI(1908)<=0.8 THEN OUTPUT D;
ELSE OUTPUT V;RUN;
PROC FREQ DATA = D;TABLES active_cust;RUN;
/*FINECLASSING FOR CONTINUOUS VARIABLE*/
%MACRO FINE_CLASS (DSN,DEPVAR,TOT_RESP,TOT_NRESP,CLASS_VAR,GRPS);                                                                             

PROC RANK DATA =&DSN. GROUPS=&GRPS. OUT=BIN_DSN;                                                                                                
VAR &CLASS_VAR.;
RANKS BIN;
RUN;

PROC SQL;
CREATE TABLE FINE_CLASSED AS SELECT
COUNT(*) AS NOBS,
MIN(&CLASS_VAR.) AS MIN_VAL,
MAX(&CLASS_VAR.) AS MAX_VAL,
SUM(CASE WHEN &DEPVAR. = 1 THEN 1 ELSE 0 END) AS RESP,
SUM(CASE WHEN &DEPVAR. = 0 THEN 1 ELSE 0 END) AS NRESP

FROM BIN_DSN

GROUP BY BIN;
QUIT;

DATA FINE_CLASSED1;
SET FINE_CLASSED;
TOT_RESP=&TOT_RESP.;
TOT_NRESP=&TOT_NRESP.;
WOE=LOG(((RESP/TOT_RESP)+0.000000001)/((NRESP/TOT_nRESP)+0.000000001));
IV=((RESP/TOT_RESP)-(NRESP/TOT_NRESP))*WOE*100;
RUN;

PROC PRINT DATA = FINE_CLASSED1;RUN;
/*PROC DELETE DATA =  FINE_CLASSED1;*/
/*PROC DELETE DATA = FINE_CLASSED;*/
/*PROC DELETE DATA = BIN_DSN;RUN;*/

%MEND;
ODS HTML FILE="C:\Documents and Settings\STD\Desktop\FB\inc.xls";
%FINE_CLASS(D,ACTIVE_CUST,46429,33864,income,10);
ODS HTML CLOSE;

